pipeline {
    agent any
    stages {
        stage("Maven build") {
            steps {
            script{
                sh 'mvn -f gatling-maven-plugin-demo-java-main/pom.xml -B clean package'
                }
            }
        }
        stage("Gatling run") {
            steps {
            script{
                sh 'mvn -f gatling-maven-plugin-demo-java-main/pom.xml -Dramp_stepOne=${params.ramp_stepOne} -Dramp_stepTwo=${params.ramp_stepTwo} -Dduring_stepOne=${params.during_stepOne} -Dduring_stepTwo=${params.during_stepTwo} -DstepOne=${params.stepOne} -DstepTwo=${params.stepTwo} gatling:test'
            }
           }
            post {
                always {
                    gatlingArchive()
                }
            }
        }
    }
}