pipeline {
    agent any
    stages {
        stage("Gatling run") {
            steps {
            script{
                sh 'mvn -f gatling-maven-plugin-demo-java-main/pom.xml -Dramp_stepOne=$ramp_stepOne -Dramp_stepTwo=$ramp_stepTwo -Dduring_stepOne=$during_stepOne -Dduring_stepTwo=$during_stepTwo -DstepOne=$stepOne -DstepTwo=$stepTwo gatling:test'
            }
           }
            post {
                always {
                    gatlingArchive()
                }
            }
        }
    }
}